- hosts: sandbox
  roles:
     - FlorianKempenich.docker
  tasks:
    - include_role:
        name: FlorianKempenich.docker
        tasks_from: dockercompose.yml
      vars:
        docker_compose_version: '1.17.0'
    - include_role:
        name: FlorianKempenich.docker
        tasks_from: dockermachine.yml
      vars:
        docker_machine_version: '0.13.0'
