- name: "docker-machine: Ensure this role is running on Ubuntu/Debian"
  assert:
    that: ansible_os_family == "Debian"
    msg: "This role only works for Ubuntu/Debian. To install Docker on Mac use GUI installer"

- name: "docker-machine: Build prequisites variables"
  set_fact:
    m_install_base_url: "https://github.com/docker/machine/releases/download"
    m_completion_base_url: "https://raw.githubusercontent.com/docker/machine"
    m_version: "v{{ docker_machine_version }}"
    m_uname_m: "{{ ansible_machine }}"
    m_uname_s: "{{ ansible_system }}"
    m_completion_dir: "{{ ansible_env.HOME }}/.zsh/completion"
    m_completion_file: "_docker-machine"

- name: "docker-machine: Build URL"
  set_fact:
    machine_install_url: >
      {{ m_install_base_url }}/{{ m_version }}/docker-machine-{{ m_uname_s }}-{{ m_uname_m }}
    machine_completion_url: >
      {{ m_completion_base_url }}/{{ m_version }}/contrib/completion/zsh/{{ m_completion_file }}

- name: "docker-machine: Install"
  get_url:
    url: "{{ machine_install_url }}"
    dest: /usr/local/bin/docker-machine
    mode: 0755
  become: yes

- name: "docker-machine: Completion"
  become: yes
  block:
    - name: "docker-machine: Completion 1/2 - Create directory"
      file:
        path: "{{ m_completion_dir }}"
        state: directory
        mode: 0755
        recurse: yes

    - name: "docker-machine: Completion 2/2 - Install completion"
      get_url:
        url: "{{ machine_completion_url }}"
        dest: "{{ m_completion_dir }}"
        mode: 0755