- name: "Ensure this role is running on Ubuntu/Debian"
  assert:
    that: ansible_os_family == "Debian"
    msg: "This role only works for Ubuntu/Debian. To install Docker on Mac use GUI installer"

- name: "Install Docker"
  become: yes
  block:
    - name: "Install requirements"
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: "Add docker GPG key"
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Add docker repo"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu  {{ ansible_lsb.codename }}  stable"
        state: present

    - name: "Install Docker-CE"
      apt:
        name: docker-ce
        update_cache: yes
        state: latest

    - name: "Add current User to the `docker` group"
      # This allows to run the `docker` commands without having to use `sudo`
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
